### ISSUE TITLE
ERR_MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by meesii** [randomairborne/r2-release#7]
![image](https://github.com/randomairborne/r2-release/assets/1815046/9643fca9-3d42-4c08-a13e-26a94eba6a8a)

**Comment by jLynx** [comment]
I am having this same issue, how did you solve it?

**Comment by meesii** [comment]
> 我也遇到了同样的问题，你是怎么解决的？

I use https://github.com/marketplace/actions/r2-upload
